#!/bin/bash

factor_rsa() {
    local n=$1
    local factors=$(factor $n)
    local primes=($(echo $factors | awk '{print $2, $3}'))
    echo "$n=${primes[0]}*${primes[1]}"
}

if [ $# -ne 1 ]; then
    echo "Usage: $0 <number>"
    exit 1
fi

n=$1
factor_rsa $n
